version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: lannister_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: lannister_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    container_name: lannister_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
